check_kube_configs:
  allow_failure: true
  image: google/cloud-sdk
  stage: test
  before_script:
    - echo "$GCLOUD_KEY" > key.json
    - gcloud auth activate-service-account --key-file key.json
    - gcloud config set compute/zone "$GCE_ZONE"
    - gcloud config set project "$GCLOUD_PROJECT"
    - gcloud container clusters get-credentials "$GCLOUD_CLUSTER"
  script:
    - kubectl create -f roles/"$TARGET_PROJECT_NAME"/deployment.yaml --dry-run
    - kubectl create -f roles/"$TARGET_PROJECT_NAME"/service.yaml --dry-run
update_remote_image:
  allow_failure: true
  image: google/cloud-sdk
  stage: deploy
  before_script:
    - echo "$GCLOUD_KEY" > key.json
    - gcloud auth activate-service-account --key-file key.json
    - gcloud config set compute/zone "$GCE_ZONE"
    - gcloud config set project "$GCLOUD_PROJECT"
    - gcloud container clusters get-credentials "$GCLOUD_CLUSTER"
  script:
    - kubectl set image deployment/"$TARGET_PROJECT_NAME"-deployment "$TARGET_PROJECT_NAME=$GCLOUD_REGISTRY_IMAGE:$TARGET_COMMIT_REF_NAME"

