---
- hosts: web
  remote_user: root
  gather_facts: False
  vars_files:
    - ../vvvvv/infra_secrets.yaml
  vars:
    containers:
      - env:
          FOO: bar
        image: 4lambda/4l-web:v1.2.4
        name: 4l-web
        networks:
          - name: 4l_iso_nw
            ipv4_address: 172.19.1.10
          - name: bridge
        published_ports:
          - "80:80/tcp"
        volumes:
          - "/opt/4l/nginx/logs:/var/log/nginx"
          - "/etc/pki/4l:/etc/pki/4l:ro"
  roles:
    - docker
