---
- hosts: unifi
  remote_user: root
  gather_facts: False
  vars_files:
    - ../vvvvv/infra_secrets.yaml
  vars:
    containers:
      - name: 4l-unifi
        env:
          CERT: /etc/pki/4l/www_4lambda_io.pem
          KEY: /etc/pki/4l/private/server.key
          PASSWORD: "{{ unifi_password }}"
        image: 4lambda/unifi:v1.0.0
        port_maps:
          - "8080:8080/tcp"
          - "8880:8880/tcp"
          - "8843:8843/tcp"
          - "8443:8443/tcp"
        volumes:
          - "/opt/4l/unifi/data:/usr/lib/unifi/data"
          - "/opt/4l/unifi/logs:/usr/lib/unifi/logs"
          - "/etc/pki/4l:/etc/pki/4l:ro"
  roles:
    - docker
