apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  selector:
    component: web
  ports:
    - name: http
      protocol: TCP
      port: 80
      nodePort: 30080
    - name: https
      protocol: TCP
      port: 443
      nodePort: 30443
  type: LoadBalancer
  loadBalancerIP: 146.148.45.233
  clusterIP: 10.3.255.2

