apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: unifi-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: web
        app: unifi
    spec:
      containers:
        - name: unifi
          image: gcr.io/1765753713/unifi:master
          env:
            - name: CERT
              value: /etc/pki/4l/www_4lambda_io.pem
            - name: KEY
              value: /etc/pki/4l/private/server.key
            - name: PASSWORD
              value: aircontrolenterprise
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8443
              protocol: TCP
            - containerPort: 8880
              protocol: TCP
            - containerPort: 8843
              protocol: TCP
          volumeMounts:
            - name: pki
              readOnly: true
              mountPath: /etc/pki/4l
            - name: unifi-persistent-data-storage
              mountPath: /usr/lib/unifi/data
            - name: unifi-persistent-log-storage
              mountPath: /usr/lib/unifi/logs
          imagePullPolicy: Always
      restartPolicy: Always
      volumes:
        - name: pki
          secret:
            secretName: ssl
            defaultMode: 0700
            items:
              - key: pem
                path: www_4lambda_io.pem
                mode: 0644
              - key: key
                path: private/server.key
                mode: 0400
        - name: unifi-persistent-data-storage
          gcePersistentDisk:
            pdName: unifi-data-disk
            fsType: ext4
        - name: unifi-persistent-log-storage
          gcePersistentDisk:
            pdName: unifi-log-disk
            fsType: ext4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
