---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unifi-deployment
  labels:
    app: unifi
spec:
  replicas: 1
  selector:
    matchLabels:
        app: unifi
  template:
    metadata:
      labels:
        app: unifi
    spec:
      containers:
        - name: unifi
          image: goofball222/unifi:release-5.7.20
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 3478
              protocol: UDP
            - containerPort: 8443
              protocol: TCP
            - containerPort: 6789
              protocol: TCP
          volumeMounts:
            - name: unifi-data-pv
              mountPath: /usr/lib/unifi/data
            - name: unifi-log-pv
              mountPath: /usr/lib/unifi/logs
          imagePullPolicy: Always
      restartPolicy: Always
      volumes:
        - name: unifi-data-pv
          persistentVolumeClaim:
            claimName: unifi-data-pvc
        - name: unifi-log-pv
          persistentVolumeClaim:
             claimName: unifi-log-pvc
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
