---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: unifi-data-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
  - ReadWriteOnce
  gcePersistentDisk:
    pdName: unifi-data-disk
    fsType: ext4
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: unifi-log-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
  - ReadWriteOnce
  gcePersistentDisk:
    pdName: unifi-log-disk
    fsType: ext4
  persistentVolumeReclaimPolicy: Retain
