---
apiVersion: v1
kind: Service
metadata:
  name: unifi-tcp-service
spec:
  selector:
    app: unifi
  ports:
    - name: unifi-device-inform
      protocol: TCP
      port: 8080
    - name: unifi-speed-test
      protocol: TCP
      port: 6789
  type: LoadBalancer
  loadBalancerIP: 146.148.43.232
---
apiVersion: v1
kind: Service
metadata:
  name: unifi-udp-service
spec:
  selector:
    app: unifi
  ports:
    - name: unifi-stun
      protocol: UDP
      port: 3478
  type: LoadBalancer
  loadBalancerIP: 146.148.43.232
