---
- name: Launch Container(s).
  become: drun
  docker:
    name: "{{ item.name }}"
    image: "{{ item.image }}"
    state: reloaded
    pull: always
    ports: "{{ item.port_maps }}"
  with_items: "{{ containers }}"
