---
- name: Ensure isolated network exists
  become: drun
  docker_network:
    name: 4l_iso_nw
    state: present
    subnet: 172.19.1.0/16

- name: Launch Container(s).
  become: drun
  docker_container:
    env: "{{ item.env }}"
    image: "{{ item.image }}"
    name: "{{ item.name }}"
    networks: "{{ item.networks }}"
    pull: true
    published_ports: "{{ item.published_ports }}"
    restart_policy: on-failure
    state: started
    volumes: "{{ item.volumes }}"
  with_items: "{{ containers }}"

- name: Set systemd Service File(s).
  template:
    src: docker-x.service
    dest:  "/etc/systemd/system/docker-{{ item.name }}.service"
  with_items: "{{ containers }}"
  notify: ENABLE CONTAINER
