---
- name: Launch Container(s).
  become: drun
  docker:
    name: "{{ item.name }}"
    image: "{{ item.image }}"
    state: reloaded
    pull: always
    ports: "{{ item.port_maps }}"
    volumes: "{{ item.volumes }}"
    restart_policy: on-failure
  when: item.group in groups
  with_items: "{{ containers }}"

- name: Set systemd Service File(s).
  template:
    src: docker-x.service
    dest:  "/etc/systemd/system/docker-{{ item.name }}.service"
  with_items: "{{ containers }}"

- name: Enable systemd Service File(s).
  systemd:
    name: "docker-{{ item.name }}.service"
    state: started
    enabled: yes
  with_items: "{{ containers }}"