---
- name: Ensure docker's repo is available.
  yum_repository:
    name: dockerrepo
    description: Docker Repository
    baseurl: https://yum.dockerproject.org/repo/main/centos/7/
    gpgkey: https://yum.dockerproject.org/gpg
    gpgcheck: yes
    enabled: yes

- name: Ensure docker-engine is installed.
  yum:
    name: docker-engine
    state: present
    update_cache: yes

- name: Set custom docker service file.
  copy:
    src: docker.service
    dest: /usr/lib/systemd/system/
  notify: RESTART SERVICE

- name: Install docker-py with pip.
  pip:
    name: docker-py>="{{ docker_py_min_version }}",<"{{ docker_py_max_version }}"
    state: present
