---
- name: Setup Hosts.
  local_action:
     module: linode
     api_key: "{{ api_key }}"
     name: "{{ inventory_hostname }}"
     plan: "{{ plan }}"
     linode_id: "{{ lid }}"
     datacenter: "{{ datacenter }}"
     distribution: "{{ distribution }}"
     password: "{{ password }}"
     ssh_pub_key: "{{ ssh.public }}"
     swap: "{{ swap }}"
     wait: yes
     state: present
