---
- name: Setup Hosts.
  local_action:
     module: linode
     api_key: "{{ api_key }}"
     name: "{{ ansible_hostname }}"
     plan: "{{ plan }}"
     datacenter: "{{ datacenter }}"
     distribution: "{{ distribution  }}"
     password: "{{ password }}"
     ssh_pub_key: "{{ ssh.public }}"
     swap: 768
     wait: yes
     wait_timeout: 600
     state: present