---
- name: Ensure docker group is present.
  group:
    name: docker
    state: present
    gid: 1900

- name: Ensure lambda group is present.
  group:
    name: lambda
    state: present
    gid: 4444

- name: Ensure 4l area exists.
  file:
    mode: 0750
    group: lambda
    path: /var/4l
    state: directory

- name: EPEL is provided.
  yum:
    name: epel-release
    state: present

- name: Ensure wanted packages are installed.
  yum:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - python-pip
    - iptables-services

- name: Disable firewalld
  systemd:
    name: firewalld
    state: stopped
    enabled: no

- name: Copy firewall rules.
  copy:
    src: "{{ item }}"
    dest: /etc/sysconfig/
  with_items:
    - iptables
    - ip6tables
  notify: IP
