---
- name: Ensure docker group is present.
  group:
    name: docker
    state: present
    gid: 1900

- name: Ensure lambda group is present.
  group:
    name: lambda
    state: present
    gid: 4444

- name: Ensure 4l area exists.
  file:
    mode: 0750
    group: lambda
    path: /var/4l
    state: directory

- name: Ensure drun user is present and in docker group.
  user:
    name: drun
    state: present
    groups: docker,lambda
    home: /home/drun
    createhome: yes
    uid: 190

- name: EPEL is provided.
  yum:
    name: epel-release
    state: present

- name: Ensure docker's repo is available.
  yum_repository:
    name: dockerrepo
    description: Docker Repository
    baseurl: https://yum.dockerproject.org/repo/main/centos/7/
    gpgkey: https://yum.dockerproject.org/gpg
    gpgcheck: yes
    enabled: yes

- name: Ensure wanted packages are installed.
  yum:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - docker-engine
    - python-pip
    - iptables-services

- name: Ensure docker.service is enabled.
  systemd:
    name: docker.service
    state: started
    enabled: yes

- name: Disable firewalld
  systemd:
    name: firewalld
    state: stopped
    enabled: no

- name: Copy firewall rules.
  copy:
    src: "{{ item }}"
    dest: /etc/sysconfig/
  with_items:
    - iptables
    - ip6tables
