---
- name: Write SSL key files.
  file:
    mode: 0750
    group: lambda
    owner: fourla
    path: /etc/pki/4l/private
    state: directory

- name: Add crt.
  copy:
    content: "{{ ssl.crt }}"
    dest: /etc/pki/4l/www_4lambda_io.crt
    group: lambda
    mode: 0644
    owner: fourla

- name: Add key.
  copy:
    content: "{{ ssl.key }}"
    dest: /etc/pki/4l/private/server.key
    group: lambda
    mode: 0644
    owner: fourla
