---
- name: Write SSL key files.
  file:
    mode: 0500
    group: lambda
    owner: fourla
    path: /etc/pki/4l/private
    state: directory

- name: Add certs.
  template:
    src: www_4lambda_io.pem
    dest: /etc/pki/4l/
    owner: fourla
    group: lambda
    mode: 0400
  no_log: True

- name: Add key.
  copy:
    content: "{{ ssl.key }}"
    dest: /etc/pki/4l/private/server.key
    group: lambda
    mode: 0400
    owner: fourla
  no_log: True
