---
- name: Ensure hosts are up.
  local_action:
     module: linode
     api_key: "{{ api_key }}"
     name: "{{ inventory_hostname_short }}"
     plan: "{{ plan }}"
     linode_id: "{{ lid }}"
     datacenter: "{{ datacenter }}"
     distribution: "{{ distribution }}"
     password: "{{ password }}"
     ssh_pub_key: "{{ ssh.public }}"
     swap: "{{ swap }}"
     wait: yes
     state: present

- name: Hosts have hostnames.
  hostname:
    name: "{{ inventory_hostname_short }}"

- name: Chicago Timezone.
  timezone:
    name: America/Chicago

- name: Setup ifcfg.
  template:
    src: ifcfg-ethx
    dest: /etc/sysconfig/network-scripts/ifcfg-eth0
  notify: NETWORK

- name: Ensure 4l users exist.
  user:
    name: "{{ item.name }}"
    state: present
    groups: "{{ item.groups }}"
    password: "{{ item.passwd }}"
    home: "{{ item.home }}"
    createhome: "{{ item.createhome }}"
    uid: "{{ item.uid }}"
  with_items: "{{ users }}"

- name: Disable password authentication.
  lineinfile:
    dest: /etc/ssh/sshd_config
    state: present
    regexp: '^PasswordAuthentication'
    line: 'PasswordAuthentication no'
  notify: SSHD
