---
- name: Ensure hosts are up.
  local_action:
     module: linode
     api_key: "{{ api_key }}"
     name: "{{ inventory_hostname_short }}"
     plan: "{{ plan }}"
     linode_id: "{{ lid }}"
     datacenter: "{{ datacenter }}"
     distribution: "{{ distribution }}"
     password: "{{ password }}"
     ssh_pub_key: "{{ ssh.public }}"
     swap: "{{ swap }}"
     wait: yes
     state: present
  when: inventory_hostname not in groups['loads']

- name: Hosts have hostnames.
  hostname:
    name: "{{ inventory_hostname_short }}"

- name: Chicago Timezone.
  timezone:
    name: America/Chicago

- name: Hosts use Google DNS.
  blockinfile:
    dest: /etc/sysconfig/network-scripts/ifcfg-eth0
    block: |
      DNS1=8.8.8.8
      DNS2=8.8.4.4
      DOMAIN=.4lambda.io
    insertafter: EOF
  register: result_net

- name: Restart Interfaces.
  systemd:
    name: network
    state: restarted
    daemon_reload: yes
  when: result_net == 'changed'

- name: Ensure 4l users exist.
  user:
    name: "{{ item.name }}"
    state: present
    groups: "{{ item.groups }}"
    password: "{{ item.passwd }}"
    home: /var/4l
    createhome: no
    uid: "{{ item.uid }}"
  with_items: "{{ users }}"

- name: Disable password authentication.
  lineinfile:
    dest: /etc/ssh/sshd_config
    state: present
    regexp: '^PasswordAuthentication'
    line: 'PasswordAuthentication no'
  register: result_ssh

- name: Restart sshd.
  systemd:
    name: ssh
    state: restarted
    daemon_reload: yes
  when: result_ssh == 'changed'
